# config/_default/menus.toml

[[main]]
name = "Days"
pageRef = "days"
weight = 10git pull

[[main]]
identifier = "github2"
pre = "github"
url = "https://github.com/nunocoracao/blowfish"
weight = 20

[[footer]]
name = "Lycée Fénelon La Rochelle"
url = "https://fenelon-notredame.com"
